require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/**/*'
    - 'vendor/bundle/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
